### ISSUE TITLE
Introduce GCode macros

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#1970] opened 2023-06-22 07:50 UTC
We have GCode templates (which I realise is an awkward name), and now I think it would be nice to start working on GCode snippets.
These are not full-blown files and likely will be limited in size.

Would be great to have a GCode editor for this.

**Comment by mkevenaar** [comment] 2024-04-08 19:36
There are currently no plans to implement this in FDM Monster. Possible duplicate of #1872

**Closed by mkevenaar** 2024-04-08 19:36 UTC
Labels: frontend, backend
