### ISSUE TITLE
Gcode storage inside FDM Monster with possibility to send gcode and launch print on one/several printers

### ISSUE THREAD

**Issue by julien-printerbox** [fdm-monster/fdm-monster#3495] opened 2024-08-23 08:56 UTC
During our daily use of our farm, we need a centralized gcode storage in order to avoid to maintain gcode storage on each printers.

We need also to launch print on one or several printers. It seems that before print, it is necessary to send gcode on the printers.

**Comment by davidzwa** [comment] 2024-12-05 09:11
@all-contributors add @julien-printerbox for idea

**Comment by davidzwa** [comment] 2024-12-14 07:42
Closing as this seems to be duplicate of #3180

**Closed by davidzwa** 2024-12-14 07:42 UTC
Labels: triage
