### ISSUE TITLE
[AutoDiscovery] SSDP based OctoPrint discovery

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#2035] opened 2023-07-03 08:09 UTC
Similar to #1686 I want to experiment with this again. 

**Help wanted**
I have implemented SSDP before, but I experienced issues where it was slow or inconsistent (mostly docker). Another doubt I had with it, when I was working on this for OctoFarm, was that I did not know how to complete the authentication triangle (asymmetric crypto / key sharing).

**Why SSDP**
It's a protocol that is supported by most networks/routers and which does not require separate brokers or applications (compared to MQTT). Furthermore, OctoPrint itself already has it built in, where as MQTT would require two plugins or a newly written plugin with the downside of having to depend on a plugin (instead of a built-in/pre-packaged feature). This does not mean I do not see the benefits of MQTT and a dedicated broker, it's just that I realize SSDP is a nice method to discover OctoPrints out of the box.

**Comment by mkevenaar** [comment] 2024-04-08 18:43
Duplicate of #1686

**Closed by mkevenaar** 2024-04-08 18:43 UTC
Labels: enhancement, help wanted, backend
